// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPNS5UyRTM-xEJpdZgazeOHO9uYaojPT0',
    appId: '1:991782859909:android:cca13393460761284d65ec',
    messagingSenderId: '991782859909',
    projectId: 'mudent-e4b72',
    storageBucket: 'mudent-e4b72.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVeeHTnFOykO9F99SJa1xcsBvo121BRyw',
    appId: '1:991782859909:ios:3d1ddc41a1508d004d65ec',
    messagingSenderId: '991782859909',
    projectId: 'mudent-e4b72',
    storageBucket: 'mudent-e4b72.appspot.com',
    iosClientId: '991782859909-qfv6ujc5o2pmnf5supt0c52imrbehajd.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
